- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  
- name: Configure hosts file
  copy:
    src: hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
    backup: yes