- name: Install Firewalld
  yum: 
    name: firewalld 
    state: present

- name: Firewalld service state
  systemd: 
    name: firewalld 
    state: restarted 
    enabled: yes

- name: Firewalld add keepalived zone
  firewalld:
    zone: keepalived
    state: present
    permanent: true

- name: Reload firewalld
  systemd:
    name: firewalld
    state: reloaded

- name: copy service VRRP
  copy:
    src: VRRP.xml
    dest: /tmp/VRRP.xml

- name: Add service from file
  shell: firewall-cmd --permanent --new-service-from-file=/tmp/VRRP.xml

- name: Firewalld add trusted ip to keepalived zone
  firewalld:
    source: "{{ hostvars[ groups['load_balancer_servers'][0] ].internal_ip }}"
    zone: keepalived
    state: enabled
    permanent: true
    immediate: true

- name: Firewalld add trusted ip to keepalived zone
  firewalld:
    source: "{{ hostvars[ groups['load_balancer_servers'][1] ].internal_ip }}"
    zone: keepalived
    state: enabled
    permanent: true
    immediate: true

- name: firewalld activate VRRP service
  firewalld:
    service: VRRP
    zone: keepalived
    permanent: true
    state: enabled

- name: Reload firewalld
  systemd:
    name: firewalld
    state: reloaded

- name: Firewalld activate HTTP service
  firewalld:
    service: http
    permanent: true
    state: enabled

- name: Firewalld activate HTTPS service
  firewalld:
    service: https
    permanent: true
    state: enabled

- name: Firewalld deactivate dhcpv6-client service
  firewalld:
    service: dhcpv6-client
    permanent: true
    state: disabled

- name: Firewalld add ssh-limited zone
  firewalld:
    zone: ssh-limited
    state: present
    permanent: true

- name: Reload firewalld
  systemd:
    name: firewalld
    state: reloaded

- name: Firewalld add trusted ip to ssh-limited zone
  firewalld:
    source: "{{ ip }}"
    zone: ssh-limited
    state: enabled
    permanent: true
    immediate: true

- name: firewalld activate ssh service
  firewalld:
    service: ssh
    zone: ssh-limited
    permanent: true
    state: enabled

- name: Firewalld deactivate ssh service
  firewalld:
    service: ssh
    permanent: true
    state: disabled

- name: Reload firewalld
  systemd:
    name: firewalld
    state: reloaded